# -*- coding: utf-8 -*-
"""No_Framework_A01283727.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z2TFTRpVN3TOWH1Qcge8VkStY8wj6PbL
"""

import pandas as pd
import numpy as np
import math

url = 'https://raw.githubusercontent.com/russelr01/Aprendizaje-Maquina/main/StudentsPerformance.csv'

data = pd.read_csv(url)
data.head()

data.columns

relevant = ['reading score', 'writing score']

data = data[relevant].copy()

x = data['reading score']
y = data['writing score']

m_x = x.mean()
data['d_x'] = m_x-x
data['d_x_sqr'] = data.d_x**2

data.head()

sum_dev_x = data.d_x_sqr.sum()

m_y = y.mean()
data['d_y'] = m_y-y

sum_dev_x_y = (data.d_x * data.d_y).sum()

m = sum_dev_x_y/sum_dev_x
m

b = m_y - m*m_x
b

score_pred = []
for i in data['reading score']:
  score_pred.append(m*i + b)

mse = ((data['writing score'] - score_pred)**2).mean()
mse

me = math.sqrt(mse)
me